name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install
        run: npm i
      - name: Lint
        run: npm run lint
